package com.yuil.game.entity.message;

public enum EntityMessageType {
	TEST,
	ADD_BTOBJECT,
	GET_ALL_BTOBJECT,
	ADD_BALL,
	REMOVE_BTOBJECT,
	UPDATE_BTOBJECT_MOTIONSTATE,
	CHANGE_AVANTAR_STATE,
	APPLY_FORCE,
	RUN_CMD,
	ADD_PLAYER,
	UPDATE_LINEAR_VELOCITY
}
